### ISSUE TITLE
[Bug]界面显示异常

### ISSUE THREAD

**Issue by pdog18** [LEOYoon-Tsaw/Squirrel-Designer#5]
<img width="556" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/17060376/233762028-b3b2be6e-deb7-4c5c-bed0-ccf9c480fae3.png">

似乎是 label font 与 font 重叠了

**Comment by LEOYoon-Tsaw** [comment]
嗯，這個不太好修，一般是連續添加、刪除字體後有概率出現。關掉重新打開App會恢復

**Comment by pdog18** [comment]
> 嗯，這個不太好修，一般是連續添加、刪除字體後有概率出現。關掉重新打開App會恢復

我是  100% 复现, 不管是否重新打开  app.

Apple M1
macOS 13.0 (22A380)

**Comment by LEOYoon-Tsaw** [comment]
你點show code，把code貼過來看看

**Comment by pdog18** [comment]
> 你點show code，把code貼過來看看

```yaml
name: "冷漠／Apathy"
font_face: "PingFangSC-Regular"
font_point: 20.0
label_font_face: "STHeitiSC-Light"
label_font_point: 29.0
comment_font_face: "PingFangSC-Regular, HanaMinB"
comment_font_point: 20.0
candidate_list_layout: linear
text_orientation: horizontal
inline_preedit: true
corner_radius: 24.0
hilited_corner_radius: 30.0
color_space: srgb
back_color: 0xFFFFFF
border_color: 0x4279AA
candidate_back_color: 0xD65658
candidate_text_color: 0xD8000000
comment_text_color: 0x999999
label_color: 0x0026FF
hilited_candidate_back_color: 0xFFF0E4
hilited_candidate_text_color: 0xEE6E00
hilited_comment_text_color: 0xFFFFFF
hilited_candidate_label_color: 0xF4994C
preedit_back_color: 0xF0BE55
text_color: 0x424242
hilited_back_color: 0xFFFD00
hilited_text_color: 0xD8000000

```
