### ISSUE TITLE
[Question] Squirrel 的 candidate_back_color 不生效?

### ISSUE THREAD

**Issue by pdog18** [LEOYoon-Tsaw/Squirrel-Designer#8]
我在调整主题配色的时候发现一个问题。我生成了一套主题配色以后发现颜色显示与预期不符，尤其是 `candidate_back_color` 。

然后我就把代码复制进 Squirrel-Designer 发现通用的代码，在 Squirrel-Designer 中的效果与 Squirrel 是不一样的。

```yaml
text_orientation: horizontal
candidate_list_layout: stacked
color_space: display_p3
candidate_format: "%c %@"
font_face: Lucida Grande
author: 雪齋 <lyc20041@gmail.com>
name: 曬經・月／Solarized Dark
hilited_text_color: 0xFFBE706D
text_color: 0xFF756E5D
hilited_back_color: 0xFFC9DADF
preedit_back_color: 0xFFD7E8ED
back_color: 0xF01660FF
border_color: 0xFF2A1F00
candidate_back_color: 0xF0EC8028
label_color: 0xFF478DF4
candidate_text_color: 0xFF7389FF
comment_text_color: 0xFFC38AFF
hilited_candidate_back_color: 0xFF403516
hilited_candidate_text_color: 0xFF989F52
hilited_candidate_label_color: 0xFFCC8947
hilited_comment_text_color: 0xFF289989
```

期望的配色:
<img width="261" alt="image" src="https://user-images.githubusercontent.com/17060376/234823002-38956ad7-2f83-4495-a399-3730b301f12f.png">

实际得到的配色:
<img width="324" alt="image" src="https://user-images.githubusercontent.com/17060376/234823098-c7917a4b-62f8-4a59-baea-864ebc8bff6a.png">

Squirrel-Design 的配色:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/17060376/234823278-954be1cb-4769-49c5-a797-1eb85b07671e.png">
