### ISSUE TITLE
请介绍页面上的皮肤分享

### ISSUE THREAD

**Issue by geekbb** [LEOYoon-Tsaw/Squirrel-Designer#9]
![image](https://user-images.githubusercontent.com/46196358/236113830-5dc89588-3b0f-47e9-8e06-04af2bd25c2e.png)
太惊艳了！！！求分享

**Comment by LEOYoon-Tsaw** [comment]
```yaml
  "preset_color_schemes/flat-light":
    name: 扁平明／Flat Light
    author: 雪齋
    color_space: display_p3
    translucency: true
    back_color: 0x1AFFFFFF
    candidate_text_color: 0xB3000000
    comment_text_color: 0x80333333
    label_color: 0xBB333333
    hilited_candidate_back_color: 0x4DFFFFFF
#    candidate_back_color: 0x2DFFFFFF
    hilited_candidate_text_color: 0x000000
    hilited_comment_text_color: 0xBF333333
    hilited_candidate_label_color: 0x000000
    preedit_back_color: 0x1A000000
    text_color: 0xBF323232
    hilited_back_color: 0x0D000000
    hilited_text_color: 0xBF1A1A1A
```
```yaml
  "preset_color_schemes/flat-dark":
    name: 扁平闇／Flat Dark
    author: 雪齋
    color_space: display_p3
    translucency: true
    back_color: 0x1A000000
    candidate_text_color: 0xB3FFFFFF
    comment_text_color: 0x80CCCCCC
    label_color: 0xBBCCCCCC
    hilited_candidate_back_color: 0x4D000000
#    candidate_back_color: 0x2D000000
    hilited_candidate_text_color: 0xFFFFFF
    hilited_comment_text_color: 0xBFCCCCCC
    hilited_candidate_label_color: 0xFFFFFF
    preedit_back_color: 0x1AFFFFFF
    text_color: 0xBFE5E5E5
    hilited_back_color: 0x0D000000
    hilited_text_color: 0xBFFFFFFF
```

**Comment by geekbb** [comment]
<img width="397" alt="image" src="https://user-images.githubusercontent.com/46196358/236360931-4d599e39-0baf-4a65-92e7-0273c730e628.png">
好像不是这个主题啊

**Comment by LEOYoon-Tsaw** [comment]
是的

**Comment by Juan-nikola** [comment]
好喜欢预览的主题，但是上面的这个看起来好像和预览的不大一样

**Comment by Juan-nikola** [comment]
> 是的

好喜欢预览的主题，但是上面的这个看起来好象和预览的不太一样

**Comment by LEOYoon-Tsaw** [comment]
哪兒不一樣？

**Comment by Juan-nikola** [comment]
> 哪兒不一樣？

是这样的
<img width="545" alt="image" src="https://user-images.githubusercontent.com/74955200/236490999-8e37de00-fa62-4257-8330-9e75d525378c.png">

**Comment by LEOYoon-Tsaw** [comment]
我只給你了配色，別的圓角大小、要不要inline_edit，自己調一下啊
高亮陰影要最新代碼編譯才能用上，或者用我fork裏編譯好的

**Comment by Juan-nikola** [comment]
好吧好吧，谢谢大佬～

**Comment by shaochenshi** [comment]
模仿着做了一个，随意取用。

  preset_color_schemes/flat_light:
    name: "扁平明／Flat Light"
    font_point: 18.0
    candidate_list_layout: linear
    text_orientation: horizontal
    inline_preedit: false
    translucency: true
    mutual_exclusive: true
    corner_radius: 15.0
    hilited_corner_radius: 13.0
    border_height: -5.0
    border_width: -5.0
    line_spacing: 4.0
    spacing: 10.0
    alpha: 100
    shadow_size: 1.0
    color_space: display_p3
    back_color: 0x1AFFFFFF
    candidate_text_color: 0xB3000000
    comment_text_color: 0x80333333
    label_color: 0xBB333333
    hilited_candidate_back_color: 0x4DFFFFFF
    hilited_candidate_text_color: 0x000000
    hilited_comment_text_color: 0xBF333333
    hilited_candidate_label_color: 0x000000
    preedit_back_color: 0x1A000000
    text_color: 0xBF323232
    hilited_text_color: 0xBF1A1A1A

**Comment by OMGljy** [comment]
> 模仿着做了一个，随意取用。
> 
> preset_color_schemes/flat_light: name: "扁平明／Flat Light" font_point: 18.0 candidate_list_layout: linear text_orientation: horizontal inline_preedit: false translucency: true mutual_exclusive: true corner_radius: 15.0 hilited_corner_radius: 13.0 border_height: -5.0 border_width: -5.0 line_spacing: 4.0 spacing: 10.0 alpha: 100 shadow_size: 1.0 color_space: display_p3 back_color: 0x1AFFFFFF candidate_text_color: 0xB3000000 comment_text_color: 0x80333333 label_color: 0xBB333333 hilited_candidate_back_color: 0x4DFFFFFF hilited_candidate_text_color: 0x000000 hilited_comment_text_color: 0xBF333333 hilited_candidate_label_color: 0x000000 preedit_back_color: 0x1A000000 text_color: 0xBF323232 hilited_text_color: 0xBF1A1A1A

哇哦，谢谢您🙏

**Comment by gandli** [comment]
# rime 仿微信输入法皮肤
<img width="600" alt="Snipaste_2024-06-15_13-21-43" src="https://github.com/LEOYoon-Tsaw/Squirrel-Designer/assets/85359251/86340f0e-179f-4e2b-9b49-ae00083f5159">
<img width="600" alt="Snipaste_2024-06-15_13-22-07" src="https://github.com/LEOYoon-Tsaw/Squirrel-Designer/assets/85359251/ec483bd3-7d5a-42bf-80bf-e984e5f907ea">

## 参考

1. [微信输入法](https://z.weixin.qq.com/)
2. [鼠鬚管介面配置指南](https://github.com/LEOYoon-Tsaw/Rime_collections/blob/master/%E9%BC%A0%E9%AC%9A%E7%AE%A1%E4%BB%8B%E9%9D%A2%E9%85%8D%E7%BD%AE%E6%8C%87%E5%8D%97.md)
3. [霞鹜文楷 GB](https://github.com/lxgw/LxgwWenkaiGB)

## 配置

```yaml
#weasel.custom.yaml

customization:
  distribution_code_name: Weasel
  distribution_version: 0.16.1
  generator: "Weasel::UIStyleSettings"
  modified_time: "Fri Jun 14 23:23:21 2024"
  rime_version: 1.11.2
patch:
  preset_color_schemes:
    ms_sogou:
      {
        author: Mark24Code,
        back_color: 0xFFFFFF,
        border_color: 0xFFFFFF,
        candidate_text_color: 0xD67F42,
        comment_text_color: 0xFFFFFF,
        hilited_back_color: 0xFFFFFF,
        hilited_candidate_back_color: 0xFFFFFF,
        hilited_candidate_text_color: 0x0D4FE9,
        hilited_text_color: 0xD9884F,
        name: "搜狗",
        text_color: 0xD9884F,
      }
    ms_wechat_dark:
      {
        author: Mark24Code,
        back_color: 0x000000,
        border_color: 0x000000,
        candidate_text_color: 0x69AD2E,
        comment_text_color: 0xFFFFFF,
        hilited_back_color: 0x69AD2E,
        hilited_candidate_back_color: 0x69AD2E,
        hilited_candidate_text_color: 0xD8D8D8,
        hilited_text_color: 0xD8D8D8,
        name: "微信dark",
        text_color: 0x69AD2E,
      }
    ms_wechat_light:
      {
        author: Mark24Code,
        back_color: 0xFFFFFF,
        border_color: 0xFFFFFF,
        candidate_text_color: 0x69AD2E,
        comment_text_color: 0xFFFFFF,
        hilited_back_color: 0x69AD2E,
        hilited_candidate_back_color: 0x69AD2E,
        hilited_candidate_text_color: 0xFFFFFF,
        hilited_text_color: 0xFFFFFF,
        name: "微信light",
        text_color: 0x69AD2E,
      }
    weType_dark:
      {
        author: wechat,
        back_color: 0x000000,
        border_color: 0x000000,
        comment_text_color: 0x999999,
        hilited_candidate_back_color: 0x75B100,
        hilited_candidate_text_color: 0xFFFFFF,
        hilited_label_color: 0xFFFFFF,
        label_color: 0x424242,
        name: "微信输入法weTypeDark",
        shadow_color: 0x20000000,
        text_color: 0xCCCCCC,
      }
    weType_light:
      {
        author: wechat,
        back_color: 0xFFFFFF,
        border_color: 0xFFDBDBDB,
        comment_text_color: 0x999999,
        hilited_candidate_back_color: 0x75B100,
        hilited_candidate_text_color: 0xFFFFFF,
        hilited_label_color: 0xFFFFFF,
        label_color: 0x888888,
        name: "微信输入法weTypeLight",
        shadow_color: 0x20000000,
        text_color: 0x333333,
      }
  style:
    candidate_format: "%c\u2005%@\u2005"
    color_scheme: weType_light
    color_scheme_dark: weType_dark
    font_face: "霞鹜文楷 GB,苹方,PingFangSC,微软雅黑"
    font_point: 14
    horizontal: true
    inline_preedit: true
    label_font_point: 10
    layout:
      {
        align_type: center,
        border: 1,
        back_radius: 10,
        corner_radius: 10,
        candidate_spacing: 11,
        hilite_padding: 2,
        hilite_padding_x: 7,
        hilite_spacing: 3,
        hilited_corner_radius: 10,
        margin_x: 12,
        margin_y: 8,
        round_corner: 10,
        shadow_radius: 5,
        spacing: 0,
      }
  "style/color_scheme": weType_light
```
